apiVersion: v1
kind: Pod
metadata:
  name: kafka-toolbox
spec:
  containers:
    - name: kafka-toolbox
      image: itadventurer/kafka-toolbox:latest
      env:
        - name: KAFKA_USER_KEY_LOCATION
          value: /var/private/ssl/kafka-client-ca-certs/user.key
        - name: KAFKA_USER_CERT_LOCATION
          value: /var/private/ssl/kafka-client-ca-certs/user.crt
        - name: KAFKA_CA_CERT_LOCATION
          value: /var/private/ssl/kafka-cluster-ca-certs/ca.crt
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{kafka-url}}"
        - name: KAFKA_ZOOKEEPER
          value: "localhost:2181"
      volumeMounts:
      - name: client-ca-certs
        mountPath: "/var/private/ssl/kafka-client-ca-certs"
        readOnly: true
      - name: cluster-ca-cert
        mountPath: "/var/private/ssl/kafka-cluster-ca-certs"
        readOnly: true
    - name: tls-sidecar
      image: 'strimzi/entity-operator-stunnel:0.11.3'
      env:
        - name: STRIMZI_ZOOKEEPER_CONNECT
          value: '{{zookeeper-url}}'
        - name: TLS_SIDECAR_LOG_LEVEL
          value: notice
      volumeMounts:
        # For Zookeeper connet
        - mountPath: "/etc/tls-sidecar/cluster-ca-certs"
          name: cluster-ca-cert
        - mountPath: "/etc/tls-sidecar/eo-certs"
          name: zk-client-cert
  volumes:
    - name: cluster-ca-cert
      secret:
        secretName: kafka-cluster-ca-cert
    - name: client-ca-certs
      secret:
        secretName: {{kafka-user}}
    - name: zk-client-cert
      secret:
        secretName: kafka-entity-operator-certs
